# Generated by Django 5.0.6 on 2024-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
