# Generated by Django 5.0.7 on 2024-10-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
