# Generated by Django 4.0.1 on 2024-10-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioatencion',
            old_name='dia',
            new_name='fecha',
        ),
    ]
