# Generated by Django 5.0.6 on 2024-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0002_alter_paciente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='responsable_area',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
