# Generated by Django 5.1.1 on 2024-10-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0002_area_alter_paciente_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='responsable_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='fisio.area'),
        ),
    ]
