# Generated by Django 5.1.2 on 2024-12-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0003_consulta_estado_prof_informe_estado_pago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoInformeArea',
        ),
    ]
