# Generated by Django 4.0.1 on 2024-11-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0003_consulta_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_operacion', models.CharField(choices=[('R', 'Recibo (Entrada)'), ('P', 'Pago (Salida)')], max_length=1)),
                ('medio_pago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Transferencia'), ('C', 'Cheque'), ('O', 'Otros')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='tarifa',
        ),
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('C', 'Cancelado'), ('P', 'Pendiente'), ('PP', 'Pago Parcial')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fisio.servicio'),
            preserve_default=False,
        ),
    ]
