# Generated by Django 4.0.1 on 2024-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0004_flujodinero_remove_cobro_tarifa_consulta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
