# Generated by Django 5.1.2 on 2024-12-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0004_delete_tipoinformearea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='apellido',
            new_name='apellido',
        ),
    ]
