# Generated by Django 4.0.1 on 2024-11-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0005_servicio_monto_delete_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujodinero',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
