# Generated by Django 5.1 on 2024-09-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0005_alter_profesional_responsable_area_horarioatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='tipo_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='fisio.profesional'),
        ),
    ]
