# Generated by Django 5.1 on 2024-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0006_alter_profesional_tipo_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='responsable_area',
            field=models.CharField(max_length=50),
        ),
    ]
