# Generated by Django 5.1 on 2024-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0007_alter_profesional_responsable_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='tipo_profesional',
        ),
    ]
