# Generated by Django 4.0.1 on 2024-11-23 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0007_rename_flujodinero_flujocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(choices=[('A', 'Asistido'), ('N', 'No Asistido')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('C', 'Cancelado'), ('P', 'Pendiente'), ('PP', 'Pago Parcial')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('cantidad_sesiones', models.IntegerField()),
                ('cantidad_realizadas', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='estado',
            new_name='estado_pago',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tiene_sesiones',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
        migrations.AddField(
            model_name='sesiones',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisio.consulta'),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisio.paciente'),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisio.servicio'),
        ),
        migrations.AddField(
            model_name='sesiondetalle',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisio.sesiones'),
        ),
    ]
