# Generated by Django 5.1.3 on 2024-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0008_sesiondetalle_sesiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='tipo',
            field=models.CharField(choices=[('E', 'Evaluación'), ('S', 'Sesión'), ('I', 'Informe')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
