# Generated by Django 5.1 on 2024-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0008_remove_profesional_tipo_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('confirmado', 'Confirmado'), ('reprogramado', 'Reprogramado'), ('cancelado_paciente', 'Cancelado por el Paciente'), ('cancelado_profesional', 'Cancelado por el Profesional'), ('no_asistido', 'No Asistido'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=30),
        ),
    ]
