# Generated by Django 5.1.3 on 2024-11-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0009_agendamiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fisio.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='profesional',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fisio.profesional'),
            preserve_default=False,
        ),
    ]
