# Generated by Django 5.1.3 on 2024-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0010_informe_paciente_informe_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='referencia_sesion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
