# Generated by Django 5.1.3 on 2024-12-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisio', '0011_agendamiento_referencia_sesion_delete_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
